name: copilot_ia
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.8.1
dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.1.0
  permission_handler: ^11.3.1
  http: ^0.13.6
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.8
  flutter_tts: ^4.0.2
  
dev_dependencies:
  flutter_test:
    sdk: flutter
dependency_overrides:
  speech_to_text_platform_interface: 2.2.0
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true